description: "test neuro-neuron dependent structure matrix modulation     noise_model_level: 1  batch_size: 8"
dataset: "signal_demo_2"

simulation:
  connectivity_type: "Lorentz"
  connectivity_init: [0, 0.1]
  external_input_type: "visual"
  external_input_mode: "multiplicative"
  params:
    [
      [1.0, 0.0, 10.0, 1.0, 1.0, 0.0],
      [1.0, 0.0, 10.0, 2.0, 2.0, 0.0],
      [2.0, 0.0, 10.0, 1.0, 4.0, 0.0],
      [2.0, 0.0, 10.0, 2.0, 8.0, 0.0],
    ]
  phi: "tanh"
  n_neurons: 2048
  n_input_neurons: 1024
  n_neuron_types: 4
  n_frames: 50000
  delta_t: 0.01
  dpos_init: 0
  boundary: "no"
  start_frame: -10000
  node_value_map: "video_bisons_32.tif"

graph_model:
  signal_model_name: "PDE_N4"
  particle_model_name: ""
  mesh_model_name: ""
  prediction: "first_derivative"

  input_size: 3
  output_size: 1
  hidden_dim: 64
  n_layers: 5

  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64

  input_size_nnr_f: 3
  n_layers_nnr_f: 5
  hidden_dim_nnr_f: 128
  output_size_nnr_f: 1
  outermost_linear_nnr_f: True
  omega_f: 30

  aggr_type: "add"
  embedding_dim: 2
  update_type: "none"

plotting:
  colormap: "tab10"
  arrow_length: 1
  xlim: [-5, 5]
  ylim: [0, 0.3]
  label_style: "greek"

claude:
  n_epochs: 2
  data_augmentation_loop: 10
  n_iter_block: 1024

training:
  n_epochs: 10
  n_runs: 1
  device: "auto"

  batch_size: 1
  small_init_batch_size: True

  data_augmentation_loop: 50

  learn_external_input: True

  sparsity: "none"
  sparsity_freq: 4
  cluster_method: "distance_plot"
  cluster_distance_threshold: 0.1
  fix_cluster_embedding: True

  coeff_W_L1: 1.0E-6
  coeff_edge_diff: 10
  coeff_update_diff: 5

  learning_rate_W_start: 2.0E-3
  learning_rate_start: 5.0E-4
  learning_rate_embedding_start: 5.0E-3

  learning_rate_NNR_f: 1.0E-5

  noise_model_level: 1
