description: "recurrent training time_step=1"
dataset: "signal_N2_1"

simulation:
  connectivity_type: "Lorentz"
  connectivity_init: [0, 0.1]
  params:
    [[10.0, 1.0, 1.0], [10.0, 2.0, 1.0], [10.0, 1.0, 2.0], [10.0, 2.0, 2.0]]
  phi: "tanh"
  n_neurons: 1000
  n_neuron_types: 4
  n_frames: 100000
  delta_t: 0.01
  dpos_init: 0
  boundary: "no"
  start_frame: -1000

graph_model:
  signal_model_name: "PDE_N2"
  particle_model_name: ""
  mesh_model_name: ""
  prediction: "first_derivative"

  input_size: 1
  output_size: 1
  hidden_dim: 64
  n_layers: 3

  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64

  aggr_type: "add"
  embedding_dim: 2
  update_type: "none"

plotting:
  colormap: "tab10"
  arrow_length: 1
  xlim: [-5, 5]
  ylim: [-8, 8]

training:
  n_epochs: 1
  n_runs: 1
  device: "cuda:1"

  recurrent_training: True
  time_step: 1

  batch_size: 8
  small_init_batch_size: False

  seed: 24

  data_augmentation_loop: 20

  sparsity: "none"
  sparsity_freq: 4
  cluster_method: "distance_plot"
  fix_cluster_embedding: True

  learning_rate_W_start: 1.0E-3
  learning_rate_start: 5.0E-4
  learning_rate_embedding_start: 7.5E-4

  coeff_W_L1: 0

claude:
  n_epochs: 1
  data_augmentation_loop: 20
  n_iter_block: 8
