description: "heterogeneity MLP0 and MLP1 slope"
dataset: "signal_fig_supp_14"

simulation:
  connectivity_type: "Lorentz"
  connectivity_init: [0, 0.1]
  # params: [a, b, g, s, w, h]
  # a: decay, b: offset, g: gain, s: self-recurrence, w: width, h: threshold   MLP1((u-h)/w)
  params:
    [
      [1.0, 0.0, 10.0, 1.0, 1.0, 0.0],
      [1.0, 0.0, 10.0, 2.0, 2.0, 0.0],
      [2.0, 0.0, 10.0, 1.0, 4.0, 0.0],
      [2.0, 0.0, 10.0, 2.0, 8.0, 0.0],
    ]
  phi: "tanh"
  n_neurons: 1000
  n_neuron_types: 4
  n_frames: 100000
  delta_t: 0.01
  dpos_init: 0
  boundary: "no"
  start_frame: -1000

graph_model:
  signal_model_name: "PDE_N5"
  particle_model_name: ""
  mesh_model_name: ""
  prediction: "first_derivative"

  input_size: 5
  output_size: 1
  hidden_dim: 64
  n_layers: 3

  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64

  aggr_type: "add"
  embedding_dim: 2
  update_type: "none"

plotting:
  colormap: "tab10"
  arrow_length: 1
  xlim: [-5, 5]
  ylim: [-8, 8]
  mlp1_xlim: [-5, 5]
  mlp1_ylim: [-1.1, 1.1]
  # MLP1 normalization: plateau detection between x=10 and x=20
  norm_method: "max"
  norm_x_start: 25.0
  norm_x_stop: 30.0

training:
  n_epochs: 20
  n_runs: 1
  device: "auto"

  batch_size: 1
  small_init_batch_size: False

  init_training_single_type: True

  seed: 24

  data_augmentation_loop: 100

  sparsity: "replace_embedding_function"
  sparsity_freq: 4
  cluster_method: "distance_plot"
  fix_cluster_embedding: True

  learning_rate_W_start: 1.0E-3
  learning_rate_start: 5.0E-4
  learning_rate_embedding_start: 2.5E-4

  coeff_edge_diff: 500
