description: designed by Claude
dataset: signal_chaotic_1_Claude
simulation:
  connectivity_type: chaotic
  connectivity_init:
  - 0
  - 0.1
  connectivity_rank: 20
  Dale_law: false
  Dale_law_factor: 0.5
  params:
  - - 1.0
    - 0.0
    - 7.0
    - 0.0
    - 1.0
    - 0.0
  - - 1.0
    - 0.0
    - 7.0
    - 0.0
    - 1.0
    - 0.0
  phi: tanh
  n_neurons: 1000
  n_neuron_types: 1
  n_frames: 10000
  delta_t: 0.01
  dpos_init: 0
  boundary: 'no'
  start_frame: -100
graph_model:
  signal_model_name: PDE_N4
  particle_model_name: ''
  mesh_model_name: ''
  prediction: first_derivative
  input_size: 3
  output_size: 1
  hidden_dim: 64
  n_layers: 3
  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64
  aggr_type: add
  embedding_dim: 2
  update_type: none
claude:
  n_epochs: 1
  data_augmentation_loop: 120
  n_iter_block: 16
  ucb_c: 1.414
plotting:
  colormap: tab10
  arrow_length: 1
  xlim:
  - -5
  - 5
  ylim:
  - -2
  - 2
training:
  n_epochs: 1
  n_runs: 1
  device: cuda:1
  batch_size: 8
  small_init_batch_size: false
  training_single_type: true
  seed: 24
  data_augmentation_loop: 120
  sparsity: replace_embedding_function
  sparsity_freq: 4
  cluster_method: distance_plot
  fix_cluster_embedding: true
  learning_rate_W_start: 6.4e-02
  learning_rate_start: 1.0e-02
  learning_rate_embedding_start: 2.5e-04
  coeff_W_L1: 1.0e-06
  coeff_edge_norm: 0.0
  coeff_edge_diff: 100
  low_rank_factorization: false
  low_rank: 100
