description: 'RNN chaotic    init_training_single_type: True    noise_model_level: 2.0 '
dataset: 'signal_N11_1_6'

simulation:
    connectivity_type: 'chaotic'
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Gaussian'
    params: [[7.0,1.0],[1.0,1.0],[1.0,1.0],[1.0,1.0]]
    phi: 'tanh'
    tau: 1.0
    n_neurons: 100
    n_neuron_types: 1
    n_frames: 10000
    delta_t: 0.1
    boundary: 'no'
    start_frame: 0

graph_model:
    signal_model_name: 'PDE_N11'
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64

    aggr_type: 'add'
    embedding_dim: 2

plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-2,2]

training:
    n_epochs: 10
    n_runs: 2
    device: 'auto'

    batch_size: 8
    small_init_batch_size: False

    seed: 24

    data_augmentation_loop: 50

    sparsity: 'none'

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3

    coeff_W_L1: 1.0E-5
    coeff_edge_norm: 0.0

    init_training_single_type: True

    noise_model_level: 2.0
    

