description: 'Gravity model with 16 different particle types'
dataset: 'signal_N'

simulation:
    connectivity_file: 'graphs_data/Brain.mat'
    params: [[0.1,0.2],[0.2,0.4]]
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 998
    n_neuron_types: 2
    n_interactions: 2
    n_frames: 1000
    delta_t: 5.0E-3
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    signal_model_name: 'PDE_N'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_layers: 3
    input_size_update: 3
    n_layers_update: 5
    hidden_dim_update: 128
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab10'
    arrow_length: 1

training:
    n_epochs: 40
    batch_size: 1
    small_init_batch_size: False
    n_runs: 2
    learning_rate_start: 0.000001
    learning_rate_end: 0.0000005
    learning_rate_embedding_start: 0.0001
    learning_rate_embedding_end: 0.0001
    sparsity: 'none'
    data_augmentation_loop: 100
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
