description: 'test sparsity + 10.000 points + noise_model_level: 1 + generic update function
synaptic network 10.000 points
1,000 sparsely (5%) connected neurons
with 4 neuron dependent update functions. Results are obtained af-
ter 20 epochs. (a) Activity time series used for GNN training. The
training dataset contains 105 time-points.'

dataset: 'signal_fig_supp6_3'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    connectivity_filling_factor: 0.05
    params: [[10.0,1.0,1.0],[10.0,2.0,1.0],[10.0,1.0,2.0],[10.0,2.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 1000
    n_neuron_types: 4
    n_frames: 10000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000
    noise_model_level: 1

graph_model:
    signal_model_name: 'PDE_N2'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 1
    output_size: 1
    hidden_dim: 64

    n_layers: 3
    input_size_update: 5
    n_layers_update: 3
    hidden_dim_update: 64
    
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'generic'


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    device: 'auto'
    n_epochs: 20
    n_runs: 2

    batch_size: 1
    small_init_batch_size: False

    data_augmentation_loop: 100

    sparsity: 'none'
#    sparsity: 'replace_embedding_function'
#    sparsity_freq: 4
#    cluster_method: 'distance_plot'
#    fix_cluster_embedding: True

    learning_rate_start: 1.0E-4
    learning_rate_embedding_start: 1.0E-4
    coeff_W_L1: 1.0E-5