description: 'neuron dependent   structure matrix'
dataset: 'signal_N4_l1'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz_structured_0.40_0.05'
    params: [[10.0,1.5,1.0,1.0,-8.0],[10.0,2.5,1.0,1.0,-7.0],[10.0,1.5,2.0,1.0,-6.0],[10.0,2.5,2.0,1.0,-5.0],
            [10.0,1.5,1.0,1.0,-4.0],[10.0,2.5,1.0,1.0,-3.0],[10.0,1.5,2.0,1.0,-2.0],[10.0,2.5,2.0,1.0,-1.0],
             [10.0,1.5,1.0,1.0,0.0],[10.0,2.5,1.0,1.0,1.0],[10.0,1.5,2.0,1.0,2.0],[10.0,2.5,2.0,1.0,3.0],
            [10.0,1.5,1.0,1.0,4.0],[10.0,2.5,1.0,1.0,5.0],[10.0,1.5,2.0,1.0,6.0],[10.0,2.5,2.0,1.0,8.0]]
    phi: 'sigmoid'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 1024
    n_nodes: 1024
    n_neuron_types: 16
    shuffle_particle_types: False
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -10000

graph_model:
    signal_model_name: 'PDE_N4'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 5

    input_size_update: 5
    n_layers_update: 5
    hidden_dim_update: 64

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'generic'
    
    lin_edge_positive: True

plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 20
    n_runs: 2
    device: 'auto'

    batch_size: 1
    small_init_batch_size: True

    epoch_reset: 2
    epoch_reset_freq: 999

    data_augmentation_loop: 50

    sparsity: 'none'
    sparsity_freq: 4
    cluster_method: 'distance_plot'
    cluster_distance_threshold: 0.1
    fix_cluster_embedding: True

    coeff_W_L1: 1.0E-5
    coeff_edge_diff: 100
    coeff_update_diff: 10

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3
    learning_rate_modulation_start: 1.0E-4

   measurement_noise_level: 1
