description: 'RNN chaotic'
dataset: 'signal_N11_3'

simulation:
    connectivity_type: 'chaotic'
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Gaussian'
    params: [[7.0,1.0],[1.0,1.0],[1.0,1.0],[1.0,1.0]]
    phi: 'tanh'
    tau: 1.0
    n_neurons: 4000
    n_neuron_types: 4
    n_frames: 100000
    delta_t: 0.1
    boundary: 'no'
    start_frame: 0
    noise_model_level: 1.0

graph_model:
    signal_model_name: 'PDE_N11'
    prediction: 'first_derivative'

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 10
    n_runs: 2
    device: 'auto'

    batch_size: 8
    small_init_batch_size: False
    data_augmentation_loop: 100

    sparsity: 'replace_embedding_function'
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    sparsity: 'replace_embedding_function'
    sparsity_freq: 4

    coeff_W_L1: 5.0E-5

    learning_rate_W_start: 1.0E-4
    learning_rate_start: 5.0E-5
    learning_rate_embedding_start: 5.0E-4
    learning_rate_modulation_start: 1.0E-4


