description: 'Whole body imaging of zebrafish 80k cells 2k time points, repeat of previous training'
dataset: 'signal_N2_WBI_small'

simulation:
    dimension: 3
    fluo_path: '/groups/saalfeld/home/allierc/signaling/WBI/subdata.h5'
    connectivity_file: ''
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    params: [[10.0,1.0],[10.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 0.0
    max_radius: 1.0E6
    n_neurons: 2056
    n_neuron_types: 2
    n_interactions: 2
    n_frames: 1598
    delta_t: 1
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    signal_model_name: 'PDE_WBI'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 5
    output_size: 1
    hidden_dim: 64
    n_layers: 3
    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab10'
    arrow_length: 1

training:
    n_epochs: 20
    batch_size: 1
    small_init_batch_size: False
    n_runs: 1
    large_range: False
    sparsity: 'none'
    sparsity_freq: 4
    data_augmentation_loop: 200
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    seed: 42
    coeff_W_L1: 1.0E-5
