description: ''
dataset: 'signal_N4_c14'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Gaussian_structured_0.40_0.01'
    params: [[10.0,1.5,1.0,1.0,-8.0],[10.0,2.5,1.0,1.0,-7.0],[10.0,1.5,2.0,1.0,-6.0],[10.0,2.5,2.0,1.0,-5.0],
            [10.0,1.5,1.0,1.0,-4.0],[10.0,2.5,1.0,1.0,-3.0],[10.0,1.5,2.0,1.0,-2.0],[10.0,2.5,2.0,1.0,-1.0],
             [10.0,1.5,1.0,1.0,0.0],[10.0,2.5,1.0,1.0,1.0],[10.0,1.5,2.0,1.0,2.0],[10.0,2.5,2.0,1.0,3.0],
            [10.0,1.5,1.0,1.0,4.0],[10.0,2.5,1.0,1.0,5.0],[10.0,1.5,2.0,1.0,6.0],[10.0,2.5,2.0,1.0,8.0]]
    phi: 'sigmoid'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 1024
    n_neuron_types: 16
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000

graph_model:
    signal_model_name: 'PDE_N4'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 64
    n_layers: 5

    lin_edge_positive: True

    input_size_update: 3
    n_layers_update: 5
    hidden_dim_update: 64

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab20'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-8,8]

training:
    n_runs: 2
    device: 'cuda:1'

    n_epochs: 10
    batch_size: 1
    small_init_batch_size: True

    epoch_reset: 2
    epoch_reset_freq: 999
    n_epochs_init: 999

    data_augmentation_loop: 10
    
    sparsity: 'none'
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    sparsity_freq: 5
    cluster_distance_threshold: 0.1

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3

    coeff_W_L1: 1.0E-5
    coeff_edge_diff: 100

   noise_model_level: 5

