description: 'Hemibrain'
dataset: 'signal_N2_hemibrain_a'

simulation:
    connectivity_file: 'conn-eb-fb-pb-no.tif'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0],[10.0,2.0,1.0],[10.0,1.0,2.0],[10.0,2.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_neurons: 2964
    n_neuron_types: 4
    n_frames: 5000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    signal_model_name: 'PDE_N2'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_layers: 3
    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab10'
    arrow_length: 1

training:
    n_epochs: 20
    batch_size: 1
    small_init_batch_size: False
    n_runs: 10
    large_range: False
    sparsity: 'replace_embedding_function'
    sparsity_freq: 4
    data_augmentation_loop: 500
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    seed: 42
    sparsity_freq: 4
    learning_rate_start: 1.0E-4
    learning_rate_embedding_start: 1.0E-4
    coeff_W_L1: 5.0E-5