description: "RNN chaotic   triggered oscillations  Dale_law   noise_model_level 1"
dataset: "signal_N4_11"

simulation:
  connectivity_type: "chaotic"
  connectivity_init: [0, 0.1]
  connectivity_distribution: "Gaussian"
  params:
    [
      [7.0, 0.0, 1.0, 1.0],
      [1.0, 0.0, 1.0, 1.0],
      [1.0, 0.0, 1.0, 1.0],
      [1.0, 0.0, 1.0, 1.0],
    ]
  phi: "tanh"
  Dale_law: True
  Dale_law_factor: 0.8

  n_neurons: 1000
  n_neuron_types: 1
  n_frames: 10000
  delta_t: 0.1
  boundary: "no"
  start_frame: -500

  input_type: "triggered"
  triggered_n_impulses: 30
  triggered_n_input_neurons: 100
  triggered_impulse_strength: 5.0
  triggered_min_start_frame: 50
  triggered_max_start_frame: 150
  triggered_duration_frames: 200
  triggered_amplitude_range: [0.5, 2.0]
  triggered_frequency_range: [0.5, 2.0]
  oscillation_frequency: 3.0
  oscillation_max_amplitude: 5.0

  n_excitatory_neurons: 1
  noise_model_level: 1

graph_model:
  signal_model_name: "PDE_N4"
  prediction: "first_derivative"

  input_size: 3
  output_size: 1
  hidden_dim: 64
  n_layers: 3

  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 64

  aggr_type: "add"
  embedding_dim: 2

  input_size_nnr_f: 1
  hidden_dim_nnr_f: 1024
  n_layers_nnr_f: 3

  outermost_linear_nnr_f: True
  output_size_nnr_f: 1

  nnr_f_xy_period: 1.0
  nnr_f_T_period: 10000
  omega_f: 1024

plotting:
  colormap: "tab10"
  arrow_length: 1
  xlim: [-5, 5]
  ylim: [-2, 2]

training:
  n_epochs: 20
  n_runs: 1
  device: "auto"

  batch_size: 16
  small_init_batch_size: False

  seed: 24

  data_augmentation_loop: 200

  sparsity: "none"

  learning_rate_W_start: 1.0E-3
  learning_rate_start: 5.0E-4
  learning_rate_embedding_start: 5.0E-3
  learning_rate_NNR_f: 1.0E-6

  coeff_W_L1: 1.0E-5
  coeff_edge_norm: 0.0

  init_training_single_type: True

